### ISSUE TITLE
[on hold] replace golang web application with a django app (~15h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/quickfix-tradeclient-web#4]
General thoughts
- my current research on the status of golang web frameworks lead me to [this fantastic reddit comment](https://www.reddit.com/r/golang/comments/5lrs4r/whats_you_goto_web_framework/dbxy87r)
- given this, I feel that we'll be better off writing the web app in [python/django](http://djangoproject.com/)
- the `tradeclient` that listens on a rabbitmq topic stays as is, and for its purposes, it doesn't care whether the application publishing the message originally to rabbitmq is another golang web app or a python django app
- I have already developed [ffa-blotter](https://github.com/teamshadi/ffa-blotter) which is a django application that allows a user to log in and create orders
- we will just need to add to it that upon saving an order, it should send a message to a rabbitmq server with the parameters expected by the `tradeclient`

Action plan
- let's split out the tradeclient here that listens to rabbitmq topic into a new repository
  - https://github.com/SSOC18/quickfix-tradeclient-rabbitmq
- learn django by following [their tutorial](https://docs.djangoproject.com/en/2.0/intro/tutorial01/)
- augment [ffa-blotter](https://github.com/teamshadi/ffa-blotter) by
    - adding a setting `TRADECLIENT_RABBITMQ=...` pointing to the rabbitmq host/port to which it can publish new orders
    - add an event fired by the `new order signal` that sends a message to the rabbitmq
    - add a django management command that listens to a rabbitmq topic for the received fills

To augment `ffa-blotter`,
- I already forked the repository at https://github.com/SSOC18/ffa-blotter
- go ahead and clone it to your desktop or on the ssoc18.teamshadi.net server
- and follow its instructions in the readme

**Comment by shadiakiki1986** [comment]
- I noticed that you're still making improvements to this web app
- any reason why you're not convinced of my points above?

**Comment by MickMek** [comment]
No improvements made on the golang web UI code, it is now in the folder `golang_webui`
Quite convinced of the points above, I have noticed that web development in golang can be a bit primitive, and with Django's rigor it will eventually be better and easier. Some modifications were made just to test out Django (created new project and app)
I'm currently just starting to look at augmenting the ffa-blotter, and will have updates soon

**Comment by shadiakiki1986** [comment]
As discussed yesterday, I may have under-estimated the difficulty of this task, given that you're new to django. Let's put this issue on hold while we tackle smaller tasks that will contribute towards your learning of django so that it would be easier for you to succeed at an issue like this one.
